- repo: https://github.com/tuandat290601/yennhavui-nextjs.git
  rev: "" # Use the sha / tag you want to point at
  hooks:
    - id: prettier
      types_or: [css, typescript]
      additional_dependencies:
        - prettier@2.1.2
        - "@prettier/plugin-xml@0.12.0"
